import type { Meal } from './data';

export type MealPhoto = {
  url: string;
  alt: string;
  source: string;
  credit?: string;
  match: 'exact' | 'close';
};

export const mealPhotoRegistry: Record<string, MealPhoto> = {
  efr: {
    url: 'https://images.unsplash.com/photo-1578160112054-954a67602b88?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080&q=80',
    alt: 'Egg Fried Rice',
    source: 'Unsplash',
    match: 'close',
  },
  csf: {
    url: 'https://images.unsplash.com/photo-1628025114288-1693ac3bcac1?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080&q=80',
    alt: 'Chicken Stir Fry',
    source: 'Unsplash',
    match: 'close',
  },
  pp: {
    url: 'https://images.unsplash.com/photo-1649952399680-21b9f6aceec7?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080&q=80',
    alt: 'Pasta Primavera',
    source: 'Unsplash',
    match: 'close',
  },
  sal: {
    url: 'https://images.unsplash.com/photo-1614627293113-e7e68163d958?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080&q=80',
    alt: 'Lemon Salmon',
    source: 'Unsplash',
    match: 'close',
  },
  'veg-omelette': {
    url: 'https://images.unsplash.com/photo-1510693206972-df098062cb71?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080&q=80',
    alt: 'Veggie Omelette',
    source: 'Unsplash',
    match: 'close',
  },
  'berry-smoothie': {
    url: 'https://images.unsplash.com/photo-1589733955941-5eeaf752f6dd?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080&q=80',
    alt: 'Berry Power Smoothie',
    source: 'Unsplash',
    match: 'close',
  },
  'tomato-soup': {
    url: 'https://images.unsplash.com/photo-1620791144170-8a443bf37a33?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080&q=80',
    alt: 'Tomato Basil Soup',
    source: 'Unsplash',
    match: 'close',
  },
  'yogurt-parfait': {
    url: 'https://images.unsplash.com/photo-1550594645-25c5bd703258?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080&q=80',
    alt: 'Berry Yogurt Parfait',
    source: 'Unsplash',
    match: 'close',
  },
  'salmon-tacos': {
    url: 'https://images.unsplash.com/photo-1512838243191-e81e8f66f1fd?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080&q=80',
    alt: 'Salmon Tacos',
    source: 'Unsplash',
    match: 'close',
  },
  'broccoli-cheddar-soup': {
    url: 'https://images.unsplash.com/photo-1626200419199-391ae4be7a41?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080&q=80',
    alt: 'Broccoli Cheddar Soup',
    source: 'Unsplash',
    match: 'close',
  },
  'veggie-stir-fry': {
    url: 'https://images.unsplash.com/photo-1634864572865-1cf8ff8bd23d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080&q=80',
    alt: 'Rainbow Veggie Stir Fry',
    source: 'Unsplash',
    match: 'close',
  },
  'quick-carbonara': {
    url: 'https://images.unsplash.com/photo-1633337474564-1d9478ca4e2e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080&q=80',
    alt: 'Quick Carbonara',
    source: 'Unsplash',
    match: 'close',
  },
  'coconut-curry': {
    url: 'https://images.unsplash.com/photo-1708782344490-9026aaa5eec7?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080&q=80',
    alt: 'Coconut Curry Chicken',
    source: 'Unsplash',
    match: 'close',
  },
  'med-bowl': {
    url: 'https://images.unsplash.com/photo-1673960802455-ec189a6207e5?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080&q=80',
    alt: 'Mediterranean Power Bowl',
    source: 'Unsplash',
    match: 'close',
  },
  'honey-mustard-chicken': {
    url: 'https://images.unsplash.com/photo-1668838195568-6a336797587f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080&q=80',
    alt: 'Honey Mustard Chicken',
    source: 'Unsplash',
    match: 'close',
  },
  frittata: {
    url: 'https://images.unsplash.com/photo-1646579933415-92109f9805df?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080&q=80',
    alt: 'Garden Frittata',
    source: 'Unsplash',
    match: 'close',
  },
  'cm-italian-spaghetti-bolognese': {
    url: 'https://www.themealdb.com/images/media/meals/sutysw1468247559.jpg',
    alt: 'Spaghetti Bolognese',
    source: 'TheMealDB',
    match: 'exact',
  },
  'cm-italian-cacio-e-pepe': {
    url: 'https://commons.wikimedia.org/wiki/Special:Redirect/file/Cacio_e_pepe.jpg?width=960',
    alt: 'Cacio e Pepe',
    source: 'Wikimedia Commons',
    match: 'exact',
  },
  'cm-italian-penne-arrabbiata': {
    url: 'https://commons.wikimedia.org/wiki/Special:Redirect/file/Penne_Arrabbiata.jpg?width=960',
    alt: 'Penne Arrabbiata',
    source: 'Wikimedia Commons',
    match: 'exact',
  },
  'cm-italian-lasagna-bolognese': {
    url: 'https://commons.wikimedia.org/wiki/Special:Redirect/file/Lasagna_bolognese.jpg?width=960',
    alt: 'Lasagna Bolognese',
    source: 'Wikimedia Commons',
    match: 'exact',
  },
  'cm-italian-mushroom-risotto': {
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Mushroom_Risotto_%284789415965%29.jpg/960px-Mushroom_Risotto_%284789415965%29.jpg',
    alt: 'Mushroom Risotto',
    source: 'Wikimedia Commons',
    match: 'exact',
  },
  'cm-italian-eggplant-parmigiana': {
    url: 'https://commons.wikimedia.org/wiki/Special:Redirect/file/Parmigiana_di_melanzane.jpg?width=960',
    alt: 'Eggplant Parmigiana',
    source: 'Wikimedia Commons',
    match: 'exact',
  },
  'cm-italian-tiramisu-french-toast': {
    url: 'https://commons.wikimedia.org/wiki/Special:Redirect/file/FrenchToast.JPG?width=960',
    alt: 'Tiramisu French Toast',
    source: 'Wikimedia Commons',
    match: 'close',
  },
  'cm-italian-italian-frittata': {
    url: 'https://commons.wikimedia.org/wiki/Special:Redirect/file/Frittata02.jpg?width=960',
    alt: 'Italian Frittata',
    source: 'Wikimedia Commons',
    match: 'close',
  },
  'cm-italian-caprese-salad': {
    url: 'https://commons.wikimedia.org/wiki/Special:Redirect/file/Caprese-1_%28tigher_crop%29.jpg?width=960',
    alt: 'Caprese Salad',
    source: 'Wikimedia Commons',
    match: 'exact',
  },
  'cm-italian-pesto-pasta-salad': {
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/Pesto_Pasta_Salad.jpg/960px-Pesto_Pasta_Salad.jpg',
    alt: 'Pesto Pasta Salad',
    source: 'Wikimedia Commons',
    match: 'exact',
  },
  'cm-italian-minestrone-soup': {
    url: 'https://commons.wikimedia.org/wiki/Special:Redirect/file/Minestrone_soup_%285%29.jpg?width=960',
    alt: 'Minestrone Soup',
    source: 'Wikimedia Commons',
    match: 'exact',
  },
  'cm-italian-chicken-piccata': {
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/16/Chicken_piccata.jpg/960px-Chicken_piccata.jpg',
    alt: 'Chicken Piccata',
    source: 'Wikimedia Commons',
    match: 'exact',
  },
  'cm-italian-bruschetta-toast': {
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1f/2014_Bruschetta_The_Larder_Chiang_Mai.jpg/960px-2014_Bruschetta_The_Larder_Chiang_Mai.jpg',
    alt: 'Bruschetta Toast',
    source: 'Wikimedia Commons',
    match: 'close',
  },
  'cm-italian-italian-wedding-soup': {
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cd/Minestra_maritata.jpg/960px-Minestra_maritata.jpg',
    alt: 'Italian Wedding Soup',
    source: 'Wikimedia Commons',
    match: 'exact',
  },
  'cm-italian-saltimbocca': {
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/29/Saltimbocca_01.jpg/960px-Saltimbocca_01.jpg',
    alt: 'Saltimbocca',
    source: 'Wikimedia Commons',
    match: 'exact',
  },
  'cm-italian-tortellini-en-brodo': {
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/Tortellini_in_brodo_Bologna.jpg/960px-Tortellini_in_brodo_Bologna.jpg',
    alt: 'Tortellini en Brodo',
    source: 'Wikimedia Commons',
    match: 'exact',
  },
  'cm-italian-polenta-with-mushrooms': {
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/03/Polenta_con_funghi.jpg/960px-Polenta_con_funghi.jpg',
    alt: 'Polenta with Mushrooms',
    source: 'Wikimedia Commons',
    match: 'exact',
  },
  'cm-italian-panzanella-salad': {
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/26/Italian_Panzanella.jpg/960px-Italian_Panzanella.jpg',
    alt: 'Panzanella Salad',
    source: 'Wikimedia Commons',
    match: 'exact',
  },
  'cm-italian-ricotta-pancakes': {
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Ricotta_Pancakes_%28211739913%29.jpeg/960px-Ricotta_Pancakes_%28211739913%29.jpeg',
    alt: 'Ricotta Pancakes',
    source: 'Wikimedia Commons',
    match: 'exact',
  },
  'cm-italian-calzone': {
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/Wikimania_2016_Deryck_day_0_-_07_calzone.jpg/960px-Wikimania_2016_Deryck_day_0_-_07_calzone.jpg',
    alt: 'Calzone',
    source: 'Wikimedia Commons',
    match: 'exact',
  },
  'cm-italian-linguine-alle-vongole': {
    url: 'https://commons.wikimedia.org/wiki/Special:Redirect/file/Linguine_alle_Vongole.jpg?width=960',
    alt: 'Linguine alle Vongole',
    source: 'Wikimedia Commons',
    match: 'exact',
  },
  'cm-italian-italian-sub-sandwich': {
    url: 'https://commons.wikimedia.org/wiki/Special:Redirect/file/Italian_sub_sandwich.jpeg?width=960',
    alt: 'Italian Sub Sandwich',
    source: 'Wikimedia Commons',
    match: 'exact',
  },
  'cm-italian-beef-carpaccio': {
    url: 'https://commons.wikimedia.org/wiki/Special:Redirect/file/Carpaccio_with_cheese_in_Warsaw.jpg?width=960',
    alt: 'Beef Carpaccio',
    source: 'Wikimedia Commons',
    match: 'close',
  },
  'cm-italian-stuffed-shells': {
    url: 'https://commons.wikimedia.org/wiki/Special:Redirect/file/2019-03-11_17_17_27_Jumbo_stuffed_shells_%28made_with_Kraft_Mozzarella_Cheese%2C_Barilla_Jumbo_Shells%2C_Prego_Italian_Sauce%2C_Maggio_Ricotta_Cheese%29_after_baking_in_Ewing_Township%2C_Mercer_County%2C_New_Jersey.jpg?width=960',
    alt: 'Stuffed Shells',
    source: 'Wikimedia Commons',
    match: 'exact',
  },
  'cm-italian-gnocchi-al-pomodoro': {
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Gnocchi_al_pomodoro_2.jpg/960px-Gnocchi_al_pomodoro_2.jpg',
    alt: 'Gnocchi al Pomodoro',
    source: 'Wikimedia Commons',
    match: 'exact',
  },
  'cm-italian-affogato-yogurt-bowl': {
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/17/Vinoteca%2C_Smithfield%2C_London_%284485849609%29.jpg/960px-Vinoteca%2C_Smithfield%2C_London_%284485849609%29.jpg',
    alt: 'Affogato Yogurt Bowl',
    source: 'Wikimedia Commons',
    match: 'close',
  },
  'cm-italian-pasta-puttanesca': {
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ac/Pasta_Puttanesca.jpg/960px-Pasta_Puttanesca.jpg',
    alt: 'Pasta Puttanesca',
    source: 'Wikimedia Commons',
    match: 'exact',
  },
  'cm-italian-italian-sausage-skillet': {
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d8/Salsiccia_Italian_pork_sausage.jpg/960px-Salsiccia_Italian_pork_sausage.jpg',
    alt: 'Italian Sausage Skillet',
    source: 'Wikimedia Commons',
    match: 'close',
  },
  'cm-mexican-chicken-tacos-al-pastor': {
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Tacos-al-Pastor.jpg/960px-Tacos-al-Pastor.jpg',
    alt: 'Chicken Tacos al Pastor',
    source: 'Wikimedia Commons',
    match: 'close',
  },
  'cm-mexican-beef-burritos': {
    url: 'https://commons.wikimedia.org/wiki/Special:Redirect/file/Smothered_beef_burrito.JPG?width=960',
    alt: 'Beef Burritos',
    source: 'Wikimedia Commons',
    match: 'close',
  },
  'cm-mexican-shrimp-quesadillas': {
    url: 'https://upload.wikimedia.org/wikipedia/commons/d/dd/06_Shrimp_Quesadilla_-_Fresco_Tortilla.jpg',
    alt: 'Shrimp Quesadillas',
    source: 'Wikimedia Commons',
    match: 'exact',
  },
  'cm-mexican-huevos-rancheros': {
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/57/Mmm...huevos_rancheros.jpg/960px-Mmm...huevos_rancheros.jpg',
    alt: 'Huevos Rancheros',
    source: 'Wikimedia Commons',
    match: 'exact',
  },
  'cm-mexican-migas': {
    url: 'https://www.themealdb.com/images/media/meals/xd9aj21740432378.jpg',
    alt: 'Migas',
    source: 'TheMealDB',
    match: 'exact',
  },
  'cm-thai-pad-thai': {
    url: 'https://www.themealdb.com/images/media/meals/rg9ze01763479093.jpg',
    alt: 'Pad Thai',
    source: 'TheMealDB',
    match: 'exact',
  },
  'cm-thai-tom-kha-gai': {
    url: 'https://www.themealdb.com/images/media/meals/ol2xxt1763582263.jpg',
    alt: 'Tom Kha Gai',
    source: 'TheMealDB',
    match: 'exact',
  },
  'cm-thai-pad-see-ew': {
    url: 'https://www.themealdb.com/images/media/meals/uuuspp1468263334.jpg',
    alt: 'Pad See Ew',
    source: 'TheMealDB',
    match: 'exact',
  },
  'cm-japanese-sesame-cucumber-salad': {
    url: 'https://www.themealdb.com/images/media/meals/93iok31766436070.jpg',
    alt: 'Sesame Cucumber Salad',
    source: 'TheMealDB',
    match: 'exact',
  },
  'cm-mediterranean-moussaka': {
    url: 'https://www.themealdb.com/images/media/meals/ctg8jd1585563097.jpg',
    alt: 'Moussaka',
    source: 'TheMealDB',
    match: 'exact',
  },
  'cm-mediterranean-shakshuka': {
    url: 'https://www.themealdb.com/images/media/meals/g373701551450225.jpg',
    alt: 'Shakshuka',
    source: 'TheMealDB',
    match: 'exact',
  },
  'cm-american-clam-chowder': {
    url: 'https://www.themealdb.com/images/media/meals/rvtvuw1511190488.jpg',
    alt: 'Clam Chowder',
    source: 'TheMealDB',
    match: 'exact',
  },
  'cm-indian-lamb-rogan-josh': {
    url: 'https://www.themealdb.com/images/media/meals/vvstvq1487342592.jpg',
    alt: 'Lamb Rogan Josh',
    source: 'TheMealDB',
    match: 'exact',
  },
  'cm-indian-tandoori-chicken': {
    url: 'https://www.themealdb.com/images/media/meals/qptpvt1487339892.jpg',
    alt: 'Tandoori Chicken',
    source: 'TheMealDB',
    match: 'exact',
  },
  'cm-chinese-kung-pao-chicken': {
    url: 'https://www.themealdb.com/images/media/meals/1525872624.jpg',
    alt: 'Kung Pao Chicken',
    source: 'TheMealDB',
    match: 'exact',
  },
  'cm-chinese-hot-and-sour-soup': {
    url: 'https://www.themealdb.com/images/media/meals/1529445893.jpg',
    alt: 'Hot and Sour Soup',
    source: 'TheMealDB',
    match: 'exact',
  },
  'cm-chinese-egg-drop-soup': {
    url: 'https://www.themealdb.com/images/media/meals/1529446137.jpg',
    alt: 'Egg Drop Soup',
    source: 'TheMealDB',
    match: 'exact',
  },
  'cm-chinese-egg-foo-young': {
    url: 'https://www.themealdb.com/images/media/meals/47y6ii1765658818.jpg',
    alt: 'Egg Foo Young',
    source: 'TheMealDB',
    match: 'exact',
  },
  'cm-french-coq-au-vin': {
    url: 'https://www.themealdb.com/images/media/meals/qstyvs1505931190.jpg',
    alt: 'Coq au Vin',
    source: 'TheMealDB',
    match: 'exact',
  },
  'cm-french-beef-bourguignon': {
    url: 'https://www.themealdb.com/images/media/meals/vtqxtu1511784197.jpg',
    alt: 'Beef Bourguignon',
    source: 'TheMealDB',
    match: 'exact',
  },
  'cm-french-ratatouille': {
    url: 'https://www.themealdb.com/images/media/meals/wrpwuu1511786491.jpg',
    alt: 'Ratatouille',
    source: 'TheMealDB',
    match: 'exact',
  },
  'cm-french-french-onion-soup': {
    url: 'https://www.themealdb.com/images/media/meals/xvrrux1511783685.jpg',
    alt: 'French Onion Soup',
    source: 'TheMealDB',
    match: 'exact',
  },
  'cm-italian-margherita-pizza': {
    url: 'https://www.themealdb.com/images/media/meals/x0lk931587671540.jpg',
    alt: 'Margherita Pizza',
    source: 'TheMealDB',
    match: 'close',
  },
  'cm-italian-osso-buco': {
    url: 'https://www.themealdb.com/images/media/meals/wwuqvt1487345467.jpg',
    alt: 'Osso Buco',
    source: 'TheMealDB',
    match: 'close',
  },
  'cm-thai-green-curry-chicken': {
    url: 'https://www.themealdb.com/images/media/meals/sstssx1487349585.jpg',
    alt: 'Green Curry Chicken',
    source: 'TheMealDB',
    match: 'close',
  },
  'cm-thai-tom-yum-soup': {
    url: 'https://www.themealdb.com/images/media/meals/l50vz41763422681.jpg',
    alt: 'Tom Yum Soup',
    source: 'TheMealDB',
    match: 'close',
  },
  'cm-thai-drunken-noodles': {
    url: 'https://www.themealdb.com/images/media/meals/2wx8cm1763373419.jpg',
    alt: 'Drunken Noodles',
    source: 'TheMealDB',
    match: 'close',
  },
  'cm-thai-massaman-curry': {
    url: 'https://www.themealdb.com/images/media/meals/tvttqv1504640475.jpg',
    alt: 'Massaman Curry',
    source: 'TheMealDB',
    match: 'close',
  },
  'cm-thai-panang-curry': {
    url: 'https://www.themealdb.com/images/media/meals/0dhtwr1763371444.jpg',
    alt: 'Panang Curry',
    source: 'TheMealDB',
    match: 'close',
  },
  'cm-thai-thai-coconut-soup': {
    url: 'https://www.themealdb.com/images/media/meals/4k8nzy1763583384.jpg',
    alt: 'Thai Coconut Soup',
    source: 'TheMealDB',
    match: 'close',
  },
  'cm-thai-shrimp-pad-kee-mao': {
    url: 'https://www.themealdb.com/images/media/meals/2wx8cm1763373419.jpg',
    alt: 'Shrimp Pad Kee Mao',
    source: 'TheMealDB',
    match: 'close',
  },
  'cm-japanese-chicken-katsu-curry': {
    url: 'https://www.themealdb.com/images/media/meals/vwrpps1503068729.jpg',
    alt: 'Chicken Katsu Curry',
    source: 'TheMealDB',
    match: 'close',
  },
  'cm-japanese-salmon-teriyaki': {
    url: 'https://www.themealdb.com/images/media/meals/xxyupu1468262513.jpg',
    alt: 'Salmon Teriyaki',
    source: 'TheMealDB',
    match: 'close',
  },
  'cm-mediterranean-stuffed-bell-peppers': {
    url: 'https://www.themealdb.com/images/media/meals/b66myb1683207208.jpg',
    alt: 'Stuffed Bell Peppers',
    source: 'TheMealDB',
    match: 'close',
  },
  'cm-american-eggs-benedict': {
    url: 'https://www.themealdb.com/images/media/meals/1550440197.jpg',
    alt: 'Eggs Benedict',
    source: 'TheMealDB',
    match: 'close',
  },
  'cm-american-pot-roast': {
    url: 'https://www.themealdb.com/images/media/meals/ursuup1487348423.jpg',
    alt: 'Pot Roast',
    source: 'TheMealDB',
    match: 'close',
  },
  'cm-american-sloppy-joes': {
    url: 'https://www.themealdb.com/images/media/meals/atd5sh1583188467.jpg',
    alt: 'Sloppy Joes',
    source: 'TheMealDB',
    match: 'close',
  },
  'cm-chinese-sweet-sour-pork': {
    url: 'https://www.themealdb.com/images/media/meals/1529442316.jpg',
    alt: 'Sweet & Sour Pork',
    source: 'TheMealDB',
    match: 'exact',
  },
  'cm-chinese-beef-and-broccoli': {
    url: 'https://www.themealdb.com/images/media/meals/m0p0j81765568742.jpg',
    alt: 'Beef and Broccoli',
    source: 'TheMealDB',
    match: 'close',
  },
  'cm-chinese-singapore-noodles': {
    url: 'https://www.themealdb.com/images/media/meals/f3cxnc1765656994.jpg',
    alt: 'Singapore Noodles',
    source: 'TheMealDB',
    match: 'close',
  },
};

export function getMealPhoto(meal: Meal): MealPhoto | null {
  return mealPhotoRegistry[meal.id] ?? null;
}
